name: Build and Push Docker Image

on:
  push:
    branches:
      - main   

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t kishxrx/gitops-argo-k8s-workflow:latest .

      - name: Push Docker image
        run: |
          docker push kishxrx/gitops-argo-k8s-workflow:latest
